"""
Canonical baseline patient payload for the Plumber /predict endpoint.

This is the known-good request structure verified against the running Plumber API.
It defines the exact field names and representative values expected by the R inference
pipeline. Use a shallow copy (BASE_PATIENT_PAYLOAD.copy()) before mutating or sending.
"""

BASE_PATIENT_PAYLOAD: dict = {
    "patientid": "TEST001",
    "mh_hypertension": 0,
    "mh_impl_dev": 0,
    "mh_bbb": 0,
    "mh_af": 1,
    "mh_stroke": 0,
    "baseline_k": 4.6,
    "age": 69,
    "mh_agina": 0,
    "arb_atccode": None,
    "arb_dose": None,
    "arni_atccode": "C09DX04",
    "arni_dose": 100,
    "ace_atccode": None,
    "ace_dose": None,
    "bb_atccode": "C07AB07",
    "bb_dose": 5,
    "mra_atccode": "C03DA01",
    "mra_dose": 12.5,
    "sglt_atccode": "A10BK03",
    "sglt_dose": 10,
    "loopd_atccode": "C03CA04",
    "loopd_dose": 5,
    "baseline_bw": 69,
    "baseline_tf": 273,
    "mh_dm": 0,
    "baseline_dpb": 64,
    "mh_cabg": 0,
    "mh_ckd": 1,
    "baseline_orthopnea": 0,
    "baseline_crp": 6.72,
    "baseline_gdf15": 1403,
    "baseline_hb_a1c": 6.1,
    "baseline_cys": 1.346,
    "baseline_rales": 0,
    "mh_mi": 0,
    "aspirin": 0,
    "sex": 0,
    "baseline_ft": 108.8,
    "baseline_chol": 167,
    "baseline_na": 144,
    "PM_Rhythm_ECG": 0,
    "baseline_urea": 55,
    "mh_vavhd": 0,
    "baseline_hct": 38.8,
    "baseline_sbp": 99,
    "baseline_hr": 66,
    "baseline_hscnt": 8.1,
    "visit_time_days": 0,
    "mh_hept": 0,
    "baseline_ntbnp": 3118,
    "lvef": 35,
    "baseline_il6": 2.65,
    "baseline_jdv": 0,
    "mh_copd": 0,
    "baseline_bmi": 26.5,
    "baseline_qrs": 110,
    "baseline_hb": 13.5,
    "baseline_creat": 1.53,
    "baseline_ischaemic": 0,
    "baseline_nyha": 2,
    "baseline_edema": 0,
    "mh_smoke": 2,
    "EP_HF_encoded": 0,
    "DoseBB_prev": 50,
    "RASDose_prev": 50,
    "DoseSpiro_prev": 100,
    "Loop_dose_prev": 0,
    "SGLT2Dose_prev": 0,
    "ARNIDose_prev": 0,
    "time_from_last_medication": 291,
}
